services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grouply-backend
    ports:
      - "1111:8080"
    networks:
      - grouply-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grouply-frontend
    depends_on:
      - backend
    ports:
      - "1212:5173"
    networks:
      - grouply-network

networks:
  grouply-network:
    driver: bridge
